///|
let dec_coeff_karatsuba_threshold = 96

///|
let dec_coeff_karatsuba_square_threshold = 96

///|
let dec_coeff_toom3_threshold = 2048

///|
let dec_coeff_ntt_mul_threshold = 4096

///|
let dec_coeff_ntt_mul_threshold_16k = 4096

///|
let dec_coeff_ntt_mul_threshold_32k = 4096

///|
let dec_coeff_ntt_mul_threshold_64k = 4096

///|
let dec_coeff_ntt_mul_threshold_large = 4096

///|
let dec_coeff_ntt_square_threshold = 2048

///|
let dec_coeff_ntt_square_threshold_8k = 2048

///|
let dec_coeff_ntt_square_threshold_16k = 2048

///|
let dec_coeff_ntt_square_threshold_32k = 2048

///|
let dec_coeff_ntt_square_threshold_64k = 2048

///|
let dec_coeff_ntt_square_threshold_large = 2048

///|
let dec_coeff_ntt_square_toom3_threshold = 4096

///|
let dec_coeff_ntt_square_toom3_threshold_8k = 4096

///|
let dec_coeff_ntt_square_toom3_threshold_16k = 4096

///|
let dec_coeff_ntt_square_toom3_threshold_32k = 4096

///|
let dec_coeff_ntt_square_toom3_threshold_64k = 4096

///|
let dec_coeff_ntt_square_toom3_threshold_large = 4096

///|
let dec_coeff_burnikel_ziegler_threshold = 2048

///|
let dec_coeff_burnikel_ziegler_threshold_8k = 2048

///|
let dec_coeff_burnikel_ziegler_threshold_16k = 2048

///|
let dec_coeff_burnikel_ziegler_threshold_large = 2048

///|
let dec_coeff_newton_threshold = 4096

///|
let dec_coeff_newton_enabled = true
