///|
let dec_coeff_karatsuba_threshold = 96

///|
let dec_coeff_karatsuba_square_threshold = 48

///|
let dec_coeff_toom3_threshold = 1152

///|
let dec_coeff_ntt_mul_threshold = 1728

///|
let dec_coeff_ntt_mul_threshold_16k = 2816

///|
let dec_coeff_ntt_mul_threshold_32k = 4608

///|
let dec_coeff_ntt_mul_threshold_64k = 7680

///|
let dec_coeff_ntt_mul_threshold_large = 8192

///|
let dec_coeff_ntt_square_threshold = 640

///|
let dec_coeff_ntt_square_threshold_8k = 1040

///|
let dec_coeff_ntt_square_threshold_16k = 1824

///|
let dec_coeff_ntt_square_threshold_32k = 3648

///|
let dec_coeff_ntt_square_threshold_64k = 7296

///|
let dec_coeff_ntt_square_threshold_large = 8192

///|
let dec_coeff_ntt_square_toom3_threshold = 8192

///|
let dec_coeff_ntt_square_toom3_threshold_8k = 8192

///|
let dec_coeff_ntt_square_toom3_threshold_16k = 1824

///|
let dec_coeff_ntt_square_toom3_threshold_32k = 3648

///|
let dec_coeff_ntt_square_toom3_threshold_64k = 7296

///|
let dec_coeff_ntt_square_toom3_threshold_large = 8192

///|
let dec_coeff_burnikel_ziegler_threshold = 2816

///|
let dec_coeff_burnikel_ziegler_threshold_8k = 5120

///|
let dec_coeff_burnikel_ziegler_threshold_16k = 10240

///|
let dec_coeff_burnikel_ziegler_threshold_large = 10240

///|
let dec_coeff_newton_threshold = 4096

///|
let dec_coeff_newton_enabled = false
